const nodemailer = require('nodemailer');

export default async function handler(req, res) {
  // التحقق من نوع الطلب
  if (req.method !== 'POST') {
    return res.status(405).json({ 
      error: 'Method not allowed. Use POST only.' 
    });
  }

  try {
    // استخراج البيانات من الطلب
    const { type, error, timestamp, app_version, user_count } = req.body;
    
    // التحقق من البيانات المطلوبة
    if (!type || !error) {
      return res.status(400).json({ 
        error: 'Missing required fields: type and error' 
      });
    }

    console.log('🚨 Alert received:', { type, error, timestamp });

    // إعداد الإيميل
    const transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: process.env.ALERT_EMAIL,
        pass: process.env.ALERT_PASSWORD
      }
    });

    // محتوى الإيميل
    const mailOptions = {
      from: process.env.ALERT_EMAIL,
      to: process.env.ALERT_EMAIL, // نفس الإيميل
      subject: `🚨 EcoVista Alert - ${type}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px;">
          <h2 style="color: #d73502;">⚠️ EcoVista API Alert</h2>
          
          <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <table style="border-collapse: collapse; width: 100%;">
              <tr style="border-bottom: 1px solid #ddd;">
                <td style="padding: 8px; font-weight: bold;">Alert Type:</td>
                <td style="padding: 8px;">${type}</td>
              </tr>
              <tr style="border-bottom: 1px solid #ddd;">
                <td style="padding: 8px; font-weight: bold;">Error Message:</td>
                <td style="padding: 8px; color: #d73502;">${error}</td>
              </tr>
              <tr style="border-bottom: 1px solid #ddd;">
                <td style="padding: 8px; font-weight: bold;">Timestamp:</td>
                <td style="padding: 8px;">${timestamp ? new Date(timestamp * 1000).toLocaleString() : 'Unknown'}</td>
              </tr>
              <tr style="border-bottom: 1px solid #ddd;">
                <td style="padding: 8px; font-weight: bold;">App Version:</td>
                <td style="padding: 8px;">${app_version || 'Unknown'}</td>
              </tr>
              <tr>
                <td style="padding: 8px; font-weight: bold;">User Count:</td>
                <td style="padding: 8px;">${user_count || 'Unknown'}</td>
              </tr>
            </table>
          </div>

          <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px;">
            <h3 style="color: #856404; margin: 0 0 10px 0;">🔧 Action Required:</h3>
            <ul style="margin: 0; padding-left: 20px;">
              <li>Check Dumpling AI dashboard immediately</li>
              <li>Verify API key and credits</li>
              <li>Consider user notification if needed</li>
            </ul>
          </div>

          <p style="margin-top: 20px; font-size: 12px; color: #666;">
            This alert was automatically generated by EcoVista iOS App.
          </p>
        </div>
      `
    };

    // إرسال الإيميل
    await transporter.sendMail(mailOptions);
    
    console.log('✅ Alert email sent successfully');
    
    // إرجاع نتيجة نجاح
    res.status(200).json({ 
      success: true, 
      message: 'Alert sent successfully',
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('❌ Error sending alert email:', error);
    
    res.status(500).json({ 
      success: false,
      error: 'Failed to send alert email',
      details: error.message
    });
  }
}
